//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_stock0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int ID_USER { get; set; }
        public string Nom_User { get; set; }
        public string Pass_Word { get; set; }
    }
}
