//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_stock0
{
    using System;
    using System.Collections.Generic;
    
    public partial class vente
    {
        public int ID_VENTE { get; set; }
        public int ID_PRODUIT { get; set; }
        public int Quantite_Vendu { get; set; }
        public System.DateTime Date_Vente { get; set; }
    
        public virtual Produit Produit { get; set; }
    }
}
